---
- name: Launch Instance
  ec2:
    group_id: '{{ ec2_server_security_group }}'
    count: '{{ ec2_server_instcount }}'
    instance_type: '{{ ec2_server_instance_type }}'
    image: '{{ ec2_server_image }}'
    wait: true
    region: '{{ ec2_server_region }}'
    keypair: '{{ ec2_server_keypair }}'
    vpc_subnet_id: '{{ ec2_server_subnet }}'
    aws_access_key: '{{ ec2_server_access_key }}'
    aws_secret_key: '{{ ec2_server_secret_key }}'
    instance_tags:
      Name: '{{ ec2_server_name }}'
  register: ec2

- name: Instance Ids
  debug: msg="{{ ec2.instance_ids }}"
